// docs/design-tokens.json → dist/tokens.css (Tailwind v4 @theme) + src/tokens.generated.ts.
//
// ponytail: a ~140-line emitter instead of style-dictionary (DESIGN_SYSTEM §2 named
// style-dictionary; approved deviation 2026-08-07). SD would need custom transforms for
// the composite typography.scale entries, the {ref} syntax, and the layout/motion groups,
// which is more configuration than this file is code. Revisit if a second platform
// (iOS/Android) needs the same tokens — that is what SD actually buys.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(here, '..', '..', 'docs', 'design-tokens.json');

const raw = JSON.parse(readFileSync(SOURCE, 'utf8'));

const kebab = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** `{color.primitive.neutral.50}` → the value at that path. References may chain. */
function deref(value, depth = 0) {
  if (typeof value !== 'string' || !value.startsWith('{')) return value;
  if (depth > 10) throw new Error(`token reference cycle at ${value}`);
  let node = raw;
  for (const key of value.slice(1, -1).split('.')) node = node?.[key];
  if (node?.$value === undefined) throw new Error(`unresolved token reference ${value}`);
  return deref(node.$value, depth + 1);
}

/** Every `$value` leaf under `node`, as [pathSegments, resolvedValue]. `_`/`$` keys are metadata. */
function* leaves(node, path = []) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('_') || key.startsWith('$')) continue;
    if (!child || typeof child !== 'object') continue;
    if ('$value' in child) yield [[...path, key], deref(child.$value)];
    else yield* leaves(child, [...path, key]);
  }
}

/** Flat `--var` → value map, in emission order. */
export function buildTokens() {
  const vars = new Map();
  const add = (name, value) => {
    if (vars.has(name)) throw new Error(`duplicate token ${name}`);
    vars.set(name, String(value));
  };
  const addAll = (node, prefix) => {
    for (const [path, value] of leaves(node)) add(`${prefix}${path.map(kebab).join('-')}`, value);
  };

  // Primitive and semantic colors share one --color-* namespace; group names don't collide.
  addAll(raw.color.primitive, '--color-');
  addAll(raw.color.semantic, '--color-');

  addAll(raw.typography.fontFamily, '--font-');
  addAll(raw.typography.fontWeight, '--font-weight-');
  for (const [name, step] of Object.entries(raw.typography.scale)) {
    if (name.startsWith('_')) continue;
    const t = `--text-${kebab(name)}`;
    // Tailwind v4 reads `--text-x--line-height` etc. as modifiers of the `text-x` utility.
    // `family` has no modifier slot — components pair the size with font-display/font-mono.
    add(t, step.fontSize);
    add(`${t}--line-height`, step.lineHeight);
    add(`${t}--font-weight`, step.fontWeight);
    if (step.letterSpacing) add(`${t}--letter-spacing`, step.letterSpacing);
  }

  addAll(raw.space, '--spacing-');
  addAll(raw.radius, '--radius-');
  addAll(raw.shadow, '--shadow-');

  addAll(raw.layout.breakpoint, '--breakpoint-');
  addAll(raw.layout.controlHeight, '--control-height-');
  for (const [path, value] of leaves(raw.layout)) {
    const [group] = path;
    if (group === 'breakpoint' || group === 'controlHeight') continue;
    add(`--layout-${path.map(kebab).join('-')}`, value);
  }

  addAll(raw.motion.duration, '--duration-');
  addAll(raw.motion.easing, '--ease-');
  // motion.reducedMotion is prose, not a value — it is honoured in globals.css.

  addAll(raw.zIndex, '--z-');
  addAll(raw.opacity, '--opacity-');

  return vars;
}

/** Resolved semantic + primitive colors, for the contrast gate. */
export function colorTokens() {
  const out = {};
  for (const [path, value] of leaves(raw.color.semantic)) out[path.join('.')] = value;
  for (const [path, value] of leaves(raw.color.primitive)) out[path.join('.')] = value;
  return out;
}

const HEADER = '/* GENERATED by packages/tokens/build.mjs from docs/design-tokens.json. Do not edit. */';

export function toCss(vars) {
  // `--x-*: initial` clears Tailwind's own palette/scale first, so `bg-slate-500`,
  // `text-sm` and `rounded-xl` stop existing and only measured tokens compile.
  const cleared = ['--color-*', '--font-*', '--text-*', '--spacing', '--spacing-*', '--radius-*', '--shadow-*', '--ease-*', '--breakpoint-*']
    .map((ns) => `  ${ns}: initial;`)
    .join('\n');
  const body = [...vars].map(([name, value]) => `  ${name}: ${value};`).join('\n');
  // `static` because Tailwind otherwise emits only the theme variables some utility
  // references — and tokens reached through inline `var()` (the avatar fills, picked
  // by hash at runtime) have no utility to be found in, so they would vanish.
  return `${HEADER}\n\n@theme static {\n${cleared}\n\n${body}\n}\n`;
}

export function toTs(vars) {
  const entries = [...vars].map(([name, value]) => `  '${name}': ${JSON.stringify(value)},`).join('\n');
  return `${HEADER}\n
export const TOKENS = {\n${entries}\n} as const;

export type TokenName = keyof typeof TOKENS;

/** \`var(--color-bg-canvas)\`, checked at compile time. */
export const token = (name: TokenName): string => \`var(\${name})\`;
`;
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const vars = buildTokens();
  mkdirSync(join(here, 'dist'), { recursive: true });
  writeFileSync(join(here, 'dist', 'tokens.css'), toCss(vars));
  writeFileSync(join(here, 'src', 'tokens.generated.ts'), toTs(vars));
  console.log(`tokens: ${vars.size} custom properties → dist/tokens.css, src/tokens.generated.ts`);
}
